-- Vinted-Dashboard (Cloud) – Supabase/Postgres-Schema.
-- Erzeugt aus apps/api/src/db/pgSchema.ts – nicht von Hand ändern.
-- Die API legt das Schema beim Start selbst an (DB_AUTO_MIGRATE); alternativ im Supabase SQL-Editor ausführen.

-- ---------- helpers ----------
CREATE OR REPLACE FUNCTION app_uid() RETURNS text LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.user_id', true), '') $$;
CREATE OR REPLACE FUNCTION app_now() RETURNS text LANGUAGE sql STABLE AS $$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') $$;

DO $$ BEGIN
  CREATE ROLE app_user NOLOGIN NOBYPASSRLS;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- The connecting role must be allowed to switch to app_user (SET LOCAL ROLE).
DO $$ BEGIN
  EXECUTE format('GRANT app_user TO %I', current_user);
EXCEPTION WHEN others THEN NULL; END $$;
GRANT USAGE ON SCHEMA public TO app_user;

-- ---------- SaaS: users, subscriptions, PC helper ----------
CREATE TABLE IF NOT EXISTS app_users (
  id TEXT PRIMARY KEY,                          -- Clerk user id (user_...)
  email TEXT,
  stripe_customer_id TEXT UNIQUE,
  stripe_subscription_id TEXT,
  subscription_status TEXT NOT NULL DEFAULT 'none', -- none | trialing | active | past_due | canceled | unpaid | incomplete
  current_period_end TEXT,
  cancel_at_period_end INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT app_now(),
  updated_at TEXT NOT NULL DEFAULT app_now()
);

ALTER TABLE app_users ADD COLUMN IF NOT EXISTS terms_accepted_at TEXT;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS terms_version TEXT;

-- "Verträge hier kündigen" (§ 312k BGB): every request is kept as proof.
CREATE TABLE IF NOT EXISTS cancellation_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('ordentlich','ausserordentlich')),
  reason TEXT,
  effective TEXT,
  result TEXT,
  received_at TEXT NOT NULL DEFAULT app_now()
);
ALTER TABLE cancellation_requests ENABLE ROW LEVEL SECURITY; -- no policies: only the server (owner) reads it

CREATE TABLE IF NOT EXISTS helper_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid() REFERENCES app_users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,              -- sha256 of the token, the token itself is shown once
  last_seen_at TEXT,
  revoked_at TEXT,
  created_at TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS helper_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  kind TEXT NOT NULL,                           -- e.g. vinted.call, assist.start
  payload TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','running','done','failed','cancelled')),
  result TEXT,
  error TEXT,
  created_at TEXT NOT NULL DEFAULT app_now(),
  started_at TEXT,
  finished_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_helper_jobs_user_status ON helper_jobs(user_id, status, id);

-- ---------- app data (same columns as the local SQLite database) ----------
CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  name TEXT NOT NULL,
  domain TEXT NOT NULL,
  username TEXT,
  vinted_user_id TEXT,
  session_encrypted TEXT,
  refresh_encrypted TEXT,
  session_hint TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','connected','error','disconnected')),
  last_error TEXT,
  last_sync_at TEXT,
  followers INTEGER NOT NULL DEFAULT 0,
  active_listings INTEGER NOT NULL DEFAULT 0,
  total_sales INTEGER NOT NULL DEFAULT 0,
  unread_messages INTEGER NOT NULL DEFAULT 0,
  publish_interval_minutes INTEGER,
  polling_enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT app_now(),
  updated_at TEXT NOT NULL DEFAULT app_now()
);

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS chrome_port INTEGER;

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  category TEXT,
  brand TEXT,
  size TEXT,
  condition TEXT,
  color TEXT,
  material TEXT,
  measurements TEXT,
  parcel_size TEXT,
  later INTEGER NOT NULL DEFAULT 0,
  price_cents INTEGER,
  currency TEXT NOT NULL DEFAULT 'EUR',
  purchase_price_cents INTEGER,
  price_suggested_cents INTEGER,
  price_suggestion_reason TEXT,
  price_confirmed INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','queued','active','sold','archived','relisted')),
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT app_now(),
  updated_at TEXT NOT NULL DEFAULT app_now()
);
CREATE INDEX IF NOT EXISTS idx_items_user_status ON items(user_id, status);

CREATE TABLE IF NOT EXISTS item_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  original_name TEXT,
  mime_type TEXT NOT NULL,
  width INTEGER,
  height INTEGER,
  size_bytes INTEGER,
  sha256 TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT app_now()
);
CREATE INDEX IF NOT EXISTS idx_item_photos_item ON item_photos(item_id, position);

CREATE TABLE IF NOT EXISTS listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  vinted_item_id TEXT,
  url TEXT,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price_cents INTEGER,
  currency TEXT NOT NULL DEFAULT 'EUR',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','sold','removed','expired','hidden')),
  favourites INTEGER NOT NULL DEFAULT 0,
  views INTEGER NOT NULL DEFAULT 0,
  listed_at TEXT NOT NULL DEFAULT app_now(),
  sold_at TEXT,
  sold_price_cents INTEGER,
  ended_at TEXT,
  last_price_drop_at TEXT,
  created_at TEXT NOT NULL DEFAULT app_now(),
  updated_at TEXT NOT NULL DEFAULT app_now(),
  UNIQUE (account_id, vinted_item_id)
);
CREATE INDEX IF NOT EXISTS idx_listings_account_status ON listings(account_id, status);
CREATE INDEX IF NOT EXISTS idx_listings_item ON listings(item_id);

CREATE TABLE IF NOT EXISTS listing_price_changes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  old_price_cents INTEGER,
  new_price_cents INTEGER NOT NULL,
  reason TEXT,
  created_at TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS publish_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  scheduled_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','done','failed','cancelled')),
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  listing_id BIGINT REFERENCES listings(id),
  is_reupload INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT app_now(),
  updated_at TEXT NOT NULL DEFAULT app_now()
);
CREATE INDEX IF NOT EXISTS idx_queue_due ON publish_queue(status, scheduled_at);

CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  listing_id BIGINT REFERENCES listings(id),
  item_id BIGINT REFERENCES items(id),
  external_id TEXT NOT NULL,
  title TEXT NOT NULL,
  price_cents INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'EUR',
  buyer TEXT,
  category TEXT,
  brand TEXT,
  sold_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT app_now(),
  UNIQUE (account_id, external_id)
);
CREATE INDEX IF NOT EXISTS idx_sales_sold_at ON sales(user_id, sold_at);

CREATE TABLE IF NOT EXISTS vinted_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  external_id TEXT NOT NULL,
  listing_id BIGINT REFERENCES listings(id),
  vinted_user_id TEXT,
  vinted_username TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  occurred_at TEXT NOT NULL,
  processed_at TEXT,
  created_at TEXT NOT NULL DEFAULT app_now(),
  UNIQUE (account_id, type, external_id)
);

CREATE TABLE IF NOT EXISTS automation_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  name TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('item_favourited','message_received','item_sold','listing_stale')),
  trigger_config TEXT NOT NULL DEFAULT '{}',
  action_type TEXT NOT NULL CHECK (action_type IN ('send_message','reduce_price')),
  action_config TEXT NOT NULL DEFAULT '{}',
  delay_minutes INTEGER NOT NULL DEFAULT 0,
  per_user_limit INTEGER NOT NULL DEFAULT 1,
  per_user_window_hours INTEGER NOT NULL DEFAULT 168,
  created_at TEXT NOT NULL DEFAULT app_now(),
  updated_at TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS scheduled_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  rule_id BIGINT REFERENCES automation_rules(id) ON DELETE SET NULL,
  event_id BIGINT REFERENCES vinted_events(id) ON DELETE SET NULL,
  account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  listing_id BIGINT REFERENCES listings(id),
  action_type TEXT NOT NULL,
  target_user_id TEXT,
  payload TEXT NOT NULL DEFAULT '{}',
  run_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done','failed','skipped','cancelled')),
  result TEXT,
  executed_at TEXT,
  created_at TEXT NOT NULL DEFAULT app_now()
);
CREATE INDEX IF NOT EXISTS idx_actions_due ON scheduled_actions(status, run_at);
CREATE INDEX IF NOT EXISTS idx_actions_limit ON scheduled_actions(rule_id, target_user_id, created_at);

CREATE TABLE IF NOT EXISTS templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'other' CHECK (kind IN ('shipping','condition','measurements','other')),
  body TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT app_now(),
  updated_at TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS settings (
  user_id TEXT NOT NULL DEFAULT app_uid(),
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  PRIMARY KEY (user_id, key)
);

CREATE TABLE IF NOT EXISTS price_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  brand TEXT,
  category TEXT,
  keyword TEXT,
  price_cents INTEGER NOT NULL,
  note TEXT,
  created_at TEXT NOT NULL DEFAULT app_now()
);

CREATE TABLE IF NOT EXISTS price_examples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT app_uid(),
  item_id BIGINT REFERENCES items(id) ON DELETE SET NULL,
  source TEXT NOT NULL CHECK (source IN ('confirmed','bulk','manual','sold')),
  title TEXT NOT NULL,
  brand TEXT,
  category TEXT,
  size TEXT,
  condition TEXT,
  price_cents INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT app_now(),
  UNIQUE (item_id, source)
);

-- ---------- row level security ----------

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON accounts;
CREATE POLICY own_rows ON accounts TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON accounts TO app_user;
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON items;
CREATE POLICY own_rows ON items TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON items TO app_user;
ALTER TABLE item_photos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON item_photos;
CREATE POLICY own_rows ON item_photos TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON item_photos TO app_user;
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON listings;
CREATE POLICY own_rows ON listings TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON listings TO app_user;
ALTER TABLE listing_price_changes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON listing_price_changes;
CREATE POLICY own_rows ON listing_price_changes TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON listing_price_changes TO app_user;
ALTER TABLE publish_queue ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON publish_queue;
CREATE POLICY own_rows ON publish_queue TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON publish_queue TO app_user;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON sales;
CREATE POLICY own_rows ON sales TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON sales TO app_user;
ALTER TABLE vinted_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON vinted_events;
CREATE POLICY own_rows ON vinted_events TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON vinted_events TO app_user;
ALTER TABLE automation_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON automation_rules;
CREATE POLICY own_rows ON automation_rules TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON automation_rules TO app_user;
ALTER TABLE scheduled_actions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON scheduled_actions;
CREATE POLICY own_rows ON scheduled_actions TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON scheduled_actions TO app_user;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON templates;
CREATE POLICY own_rows ON templates TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON templates TO app_user;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON settings;
CREATE POLICY own_rows ON settings TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON settings TO app_user;
ALTER TABLE price_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON price_rules;
CREATE POLICY own_rows ON price_rules TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON price_rules TO app_user;
ALTER TABLE price_examples ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON price_examples;
CREATE POLICY own_rows ON price_examples TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON price_examples TO app_user;
ALTER TABLE helper_tokens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON helper_tokens;
CREATE POLICY own_rows ON helper_tokens TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON helper_tokens TO app_user;
ALTER TABLE helper_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_rows ON helper_jobs;
CREATE POLICY own_rows ON helper_jobs TO app_user USING (user_id = app_uid()) WITH CHECK (user_id = app_uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON helper_jobs TO app_user;

ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS own_row ON app_users;
CREATE POLICY own_row ON app_users TO app_user USING (id = app_uid());
GRANT SELECT ON app_users TO app_user;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;
